# Generated by Django 4.1.7 on 2023-06-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_movie_actors_alter_actor_slug_alter_director_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='director',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
